echo ""
echo "  [*]  To.Panga Uninstaller "
echo "  [-]  @DeclanLand"
echo ""

rm -f /bin/bash 
rm -f /bin/dd 
rm -f /bin/ln 
rm -f /bin/sed 
rm -f /bin/vdir 
rm -f /bin/bunzip2 
rm -f /bin/dir 
rm -f /bin/ls 
rm -f /bin/sh 
rm -f /bin/zcat 
rm -f /bin/bzcat 
rm -f /bin/echo 
rm -f /bin/mkdir 
rm -f /bin/sleep 
rm -f /bin/zcmp 
rm -f /bin/bzip2 
rm -f /bin/egrep 
rm -f /bin/mknod 
rm -f /bin/stty 
rm -f /bin/zdiff 
rm -f /bin/bzip2recover 
rm -f /bin/false 
rm -f /bin/mktemp 
rm -f /bin/su 
rm -f /bin/zegrep 
rm -f /bin/cat 
rm -f /bin/fgrep 
rm -f /bin/mv 
rm -f /bin/sync 
rm -f /bin/zfgrep 
rm -f /bin/chgrp 
rm -f /bin/grep 
rm -f /bin/pwd 
rm -f /bin/tar 
rm -f /bin/zforce 
rm -f /bin/chmod 
rm -f /bin/gunzip 
rm -f /bin/readlink 
rm -f /bin/touch 
rm -f /bin/zgrep 
rm -f /bin/chown 
rm -f /bin/gzexe 
rm -f /bin/rm 
rm -f /bin/true 
rm -f /bin/zless 
rm -f /bin/cp 
rm -f /bin/gzip 
rm -f /bin/rmdir 
rm -f /bin/uname 
rm -f /bin/zmore 
rm -f /bin/date 
rm -f /bin/kill 
rm -f /bin/run-parts 
rm -f /bin/uncompress 
rm -f /bin/znew 
rm -f /Library/LaunchDaemons/0.reload.plist 
rm -f /Library/LaunchDaemons/com.saurik.Cydia.Startup.plist 
rm -f /Library/LaunchDaemons/dropbear.plist 
rm -f /Library/MobileSubstrate/DynamicLibraries/patcyh.dylib 
rm -f /Library/MobileSubstrate/DynamicLibraries/patcyh.plist 
rm -f /private/etc/alternatives/README 
rm -f /private/etc/apt/sources.list.d/cydia.list 
rm -f /private/etc/apt/sources.list.d/saurik.list 
rm -f /private/etc/apt/trustdb.gpg 
rm -f /private/etc/apt/trusted.gpg 
rm -f /private/etc/apt/trusted.gpg.d/bigboss.gpg 
rm -f /private/etc/apt/trusted.gpg.d/modmyi.gpg 
rm -f /private/etc/apt/trusted.gpg.d/saurik.gpg 
rm -f /private/etc/apt/trusted.gpg.d/zodttd.gpg 
rm -f /private/etc/dpkg/origins/debian 
rm -f /private/etc/pam.d/chkpasswd 
rm -f /private/etc/pam.d/sshd 
rm -f /private/etc/pam.d/other 
rm -f /private/etc/pam.d/su 
rm -f /private/etc/pam.d/samba 
rm -f /private/etc/pam.d/sudo 
rm -f /private/etc/pam.d/login 
rm -f /private/etc/pam.d/passwd 
rm -f /private/etc/profile 
rm -f /private/etc/profile.d/terminal.sh 
rm -f /private/var/lib/dpkg/available 
rm -f /private/var/lib/dpkg/info/readline.list 
rm -f /private/var/lib/dpkg/info/uikittools.list 
rm -f /private/var/lib/dpkg/info/debianutils.list 
rm -f /private/var/lib/dpkg/info/profile.d.list 
rm -f /private/var/lib/dpkg/info/lzma.list 
rm -f /private/var/lib/dpkg/info/dpkg.list 
rm -f /private/var/lib/dpkg/info/base.extrainst_ 
rm -f /private/var/lib/dpkg/info/bzip2.list 
rm -f /private/var/lib/dpkg/info/ncurses.preinst 
rm -f /private/var/lib/dpkg/info/firmware-sbin.preinst 
rm -f /private/var/lib/dpkg/info/apt7-key.list 
rm -f /private/var/lib/dpkg/info/shell-cmds.list 
rm -f /private/var/lib/dpkg/info/ncurses.prerm 
rm -f /private/var/lib/dpkg/info/pam.preinst 
rm -f /private/var/lib/dpkg/info/pam-modules.list 
rm -f /private/var/lib/dpkg/info/com.saurik.patcyh.list 
rm -f /private/var/lib/dpkg/info/coreutils-bin.list 
rm -f /private/var/lib/dpkg/info/grep.list 
rm -f /private/var/lib/dpkg/info/cydia.preinst 
rm -f /private/var/lib/dpkg/info/cydia.postinst 
rm -f /private/var/lib/dpkg/info/cydia-lproj.list 
rm -f /private/var/lib/dpkg/info/system-cmds.list 
rm -f /private/var/lib/dpkg/info/gnupg.list 
rm -f /private/var/lib/dpkg/info/cydia.list 
rm -f /private/var/lib/dpkg/info/firmware-sbin.list 
rm -f /private/var/lib/dpkg/info/sed.list 
rm -f /private/var/lib/dpkg/info/tar.list 
rm -f /private/var/lib/dpkg/info/firmware-sbin.extrainst_ 
rm -f /private/var/lib/dpkg/info/findutils.list 
rm -f /private/var/lib/dpkg/info/com.saurik.patcyh.postrm 
rm -f /private/var/lib/dpkg/info/apt7-lib.list 
rm -f /private/var/lib/dpkg/info/pam.list 
rm -f /private/var/lib/dpkg/info/com.saurik.patcyh.extrainst_ 
rm -f /private/var/lib/dpkg/info/uikittools.extrainst_ 
rm -f /private/var/lib/dpkg/info/bash.list 
rm -f /private/var/lib/dpkg/info/diffutils.list 
rm -f /private/var/lib/dpkg/info/darwintools.list 
rm -f /private/var/lib/dpkg/info/ncurses.list 
rm -f /private/var/lib/dpkg/info/org.thebigboss.repo.icons.list 
rm -f /private/var/lib/dpkg/info/ldid.list 
rm -f /private/var/lib/dpkg/info/firmware-sbin.postrm 
rm -f /private/var/lib/dpkg/info/pam-modules.preinst 
rm -f /private/var/lib/dpkg/info/base.list 
rm -f /private/var/lib/dpkg/info/gzip.list 
rm -f /private/var/lib/dpkg/status 
rm -f /private/var/run/utmp 
rm -f /sbin/reboot 
rm -f /sbin/halt 
rm -f /sbin/dmesg 
rm -f /sbin/dynamic_pager 
rm -f /sbin/nologin 
rm -f /usr/bin/lzmainfo 
rm -f /usr/bin/iomfsetgamma 
rm -f /usr/bin/chsh 
rm -f /usr/bin/gpgv 
rm -f /usr/bin/toe 
rm -f /usr/bin/cmp 
rm -f /usr/bin/locate 
rm -f /usr/bin/cfversion 
rm -f /usr/bin/gpg-zip 
rm -f /usr/bin/dselect 
rm -f /usr/bin/infotocap 
rm -f /usr/bin/ncursesw5-config 
rm -f /usr/bin/dpkg-deb 
rm -f /usr/bin/diff3 
rm -f /usr/bin/sw_vers 
rm -f /usr/bin/gpg 
rm -f /usr/bin/df 
rm -f /usr/bin/renice 
rm -f /usr/bin/captoinfo 
rm -f /usr/bin/dpkg-name 
rm -f /usr/bin/bashbug 
rm -f /usr/bin/dpkg-split 
rm -f /usr/bin/chfn 
rm -f /usr/bin/tset 
rm -f /usr/bin/unlzma 
rm -f /usr/bin/uicache 
rm -f /usr/bin/reset 
rm -f /usr/bin/pagesize 
rm -f /usr/bin/gpgsplit 
rm -f /usr/bin/diff 
rm -f /usr/bin/uiopen 
rm -f /usr/bin/dpkg-trigger 
rm -f /usr/bin/updatedb 
rm -f /usr/bin/ncurses5-config 
rm -f /usr/bin/script 
rm -f /usr/bin/ldrestart 
rm -f /usr/bin/time 
rm -f /usr/bin/sbdidlaunch 
rm -f /usr/bin/clear 
rm -f /usr/bin/tic 
rm -f /usr/bin/getconf 
rm -f /usr/bin/killall 
rm -f /usr/bin/lzless 
rm -f /usr/bin/dpkg-query 
rm -f /usr/bin/infocmp 
rm -f /usr/bin/lzcmp 
rm -f /usr/bin/arch 
rm -f /usr/bin/xargs 
rm -f /usr/bin/getty 
rm -f /usr/bin/lzcat 
rm -f /usr/bin/ldid 
rm -f /usr/bin/uiduid 
rm -f /usr/bin/dirname 
rm -f /usr/bin/lzdiff 
rm -f /usr/bin/find 
rm -f /usr/bin/lzmadec 
rm -f /usr/bin/lzgrep 
rm -f /usr/bin/sdiff 
rm -f /usr/bin/lzmore 
rm -f /usr/bin/tput 
rm -f /usr/bin/lzfgrep 
rm -f /usr/bin/hostinfo 
rm -f /usr/bin/tar 
rm -f /usr/bin/lzma 
rm -f /usr/bin/sbreload 
rm -f /usr/bin/login 
rm -f /usr/bin/which 
rm -f /usr/bin/gssc 
rm -f /usr/bin/apt-key 
rm -f /usr/bin/lzegrep 
rm -f /usr/bin/passwd 
rm -f /usr/bin/dpkg 
rm -f /usr/include/termcap.h 
rm -f /usr/include/cursesp.h 
rm -f /usr/include/cursesf.h 
rm -f /usr/include/etip.h 
rm -f /usr/include/form.h 
rm -f /usr/include/cursesw.h 
rm -f /usr/include/nc_tparm.h 
rm -f /usr/include/readline/readline.h 
rm -f /usr/include/readline/keymaps.h 
rm -f /usr/include/readline/tilde.h 
rm -f /usr/include/readline/rlconf.h 
rm -f /usr/include/readline/chardefs.h 
rm -f /usr/include/readline/history.h 
rm -f /usr/include/readline/rlstdc.h 
rm -f /usr/include/readline/rltypedefs.h 
rm -f /usr/include/unctrl.h 
rm -f /usr/include/cursesapp.h 
rm -f /usr/include/pam/pam_appl.h 
rm -f /usr/include/pam/pam_modules.h 
rm -f /usr/include/pam/_pam_types.h 
rm -f /usr/include/pam/_pam_macros.h 
rm -f /usr/include/pam/_pam_compat.h 
rm -f /usr/include/pam/pam_mod_misc.h 
rm -f /usr/include/pam/_pam_aconf.h 
rm -f /usr/include/term.h 
rm -f /usr/include/cursslk.h 
rm -f /usr/include/panel.h 
rm -f /usr/include/ncurses.h 
rm -f /usr/include/tic.h 
rm -f /usr/include/eti.h 
rm -f /usr/include/ncurses_dll.h 
rm -f /usr/include/term_entry.h 
rm -f /usr/include/menu.h 
rm -f /usr/include/lzmadec.h 
rm -f /usr/include/cursesm.h 
rm -f /usr/include/ncursesw 
rm -f /usr/include/ncursesw/termcap.h 
rm -f /usr/include/ncursesw/cursesp.h 
rm -f /usr/include/ncursesw/cursesf.h 
rm -f /usr/include/ncursesw/etip.h 
rm -f /usr/include/ncursesw/form.h 
rm -f /usr/include/ncursesw/cursesw.h 
rm -f /usr/include/ncursesw/nc_tparm.h 
rm -f /usr/include/ncursesw/unctrl.h 
rm -f /usr/include/ncursesw/cursesapp.h 
rm -f /usr/include/ncursesw/term.h 
rm -f /usr/include/ncursesw/cursslk.h 
rm -f /usr/include/ncursesw/panel.h 
rm -f /usr/include/ncursesw/ncurses.h 
rm -f /usr/include/ncursesw/tic.h 
rm -f /usr/include/ncursesw/eti.h 
rm -f /usr/include/ncursesw/ncurses_dll.h 
rm -f /usr/include/ncursesw/term_entry.h 
rm -f /usr/include/ncursesw/menu.h 
rm -f /usr/include/ncursesw/cursesm.h 
rm -f /usr/include/ncursesw/curses.h 
rm -f /usr/include/curses.h 
rm -f /usr/lib/libhistory.5.dylib 
rm -f /usr/lib/libapt-pkg.dylib.4.6 
rm -f /usr/lib/libpam.dylib 
rm -f /usr/lib/libpamc.1.dylib 
rm -f /usr/lib/libapt-pkg.dylib.4.6.0 
rm -f /usr/lib/libpanelw.5.dylib 
rm -f /usr/lib/libhistory.5.2.dylib 
rm -f /usr/lib/libreadline.6.dylib 
rm -f /usr/lib/libpanel.dylib 
rm -f /usr/lib/libapt-inst.dylib.1.1 
rm -f /usr/lib/libcurses.dylib 
rm -f /usr/lib/liblzmadec.0.dylib 
rm -f /usr/lib/libhistory.6.dylib 
rm -f /usr/lib/libformw.dylib 
rm -f /usr/lib/libncursesw.dylib 
rm -f /usr/lib/libapt-inst.dylib 
rm -f /usr/lib/libncurses.5.dylib 
rm -f /usr/lib/libapt-pkg.dylib 
rm -f /usr/lib/libreadline.5.dylib 
rm -f /usr/lib/libhistory.6.0.dylib 
rm -f /usr/lib/libform.5.dylib 
rm -f /usr/lib/libpanelw.dylib 
rm -f /usr/lib/pam/pam_wheel.so 
rm -f /usr/lib/pam/pam_securetty.so 
rm -f /usr/lib/pam/pam_deny.so 
rm -f /usr/lib/pam/pam_rootok.so 
rm -f /usr/lib/pam/pam_uwtmp.so 
rm -f /usr/lib/pam/pam_launchd.so 
rm -f /usr/lib/pam/pam_unix.so 
rm -f /usr/lib/pam/pam_permit.so 
rm -f /usr/lib/pam/pam_nologin.so 
rm -f /usr/lib/libmenuw.dylib 
rm -f /usr/lib/libform.dylib 
rm -f /usr/lib/terminfo 
rm -f /usr/lib/libpam.1.0.dylib 
rm -f /usr/lib/libmenu.5.dylib 
rm -f /usr/lib/libpatcyh.dylib 
rm -f /usr/lib/libreadline.6.0.dylib 
rm -f /usr/lib/liblzmadec.dylib 
rm -f /usr/lib/apt/methods 
rm -f /usr/lib/apt/methods/gpgv 
rm -f /usr/lib/apt/methods/https 
rm -f /usr/lib/apt/methods/ftp 
rm -f /usr/lib/apt/methods/cdrom 
rm -f /usr/lib/apt/methods/file 
rm -f /usr/lib/apt/methods/rsh 
rm -f /usr/lib/apt/methods/gzip 
rm -f /usr/lib/apt/methods/ssh 
rm -f /usr/lib/apt/methods/http 
rm -f /usr/lib/apt/methods/copy 
rm -f /usr/lib/apt/methods/rred 
rm -f /usr/lib/apt/methods/lzma 
rm -f /usr/lib/apt/methods/bzip2 
rm -f /usr/lib/libncurses.dylib 
rm -f /usr/lib/libhistory.dylib 
rm -f /usr/lib/libpamc.dylib 
rm -f /usr/lib/libformw.5.dylib 
rm -f /usr/lib/libapt-inst.dylib.1.1.0 
rm -f /usr/lib/libpanel.5.dylib 
rm -f /usr/lib/liblzmadec.0.0.0.dylib 
rm -f /usr/lib/_ncurses 
rm -f /usr/lib/libpam_misc.1.dylib 
rm -f /usr/lib/libreadline.5.2.dylib 
rm -f /usr/lib/libpam_misc.dylib 
rm -f /usr/lib/libreadline.dylib 
rm -f /usr/lib/libmenuw.5.dylib 
rm -f /usr/lib/libpam.1.dylib 
rm -f /usr/lib/libmenu.dylib 
rm -f /usr/lib/liblzmadec.la 
rm -f /usr/lib/dpkg/methods/apt/install 
rm -f /usr/lib/dpkg/methods/apt/names 
rm -f /usr/lib/dpkg/methods/apt/update 
rm -f /usr/lib/dpkg/methods/apt/desc.apt 
rm -f /usr/lib/dpkg/methods/apt/setup 
rm -f /usr/lib/libncursesw.5.dylib 
rm -f /usr/libexec/cydia/setnsfpn 
rm -f /usr/libexec/cydia/cfversion 
rm -f /usr/libexec/cydia/free.sh 
rm -f /usr/libexec/cydia/move.sh 
rm -f /usr/libexec/cydia/du 
rm -f /usr/libexec/cydia/asuser 
rm -f /usr/libexec/cydia/finish.sh 
rm -f /usr/libexec/cydia/firmware.sh 
rm -f /usr/libexec/cydia/startup 
rm -f /usr/libexec/cydia/cydo 
rm -f /usr/libexec/frcode 
rm -f /usr/libexec/bigram 
rm -f /usr/libexec/code 
rm -f /usr/libexec/reload 
rm -f /usr/libexec/gnupg/gpgkeys_hkp 
rm -f /usr/libexec/gnupg/gpgkeys_finger 
rm -f /usr/libexec/gnupg/gpgkeys_curl 
rm -f /usr/libexec/rmt 
rm -f /usr/local/bin/dropbear 
rm -f /usr/local/bin/dropbearkey 
rm -f /usr/local/bin/dropbearconvert 
rm -f /usr/sbin/accton 
rm -f /usr/sbin/vifs 
rm -f /usr/sbin/ac 
rm -f /usr/sbin/update 
rm -f /usr/sbin/pwd_mkdb 
rm -f /usr/sbin/sysctl 
rm -f /usr/sbin/zdump 
rm -f /usr/sbin/startupfiletool 
rm -f /usr/sbin/iostat 
rm -f /usr/sbin/mkfile 
rm -f /usr/sbin/zic 
rm -f /usr/sbin/vipw 
rm -f /usr/share/bigboss/icons/planetiphones.png 
rm -f /usr/share/bigboss/icons/bigboss.png 
rm -f /usr/share/bigboss/icons/touchrev.png 
rm -f /usr/share/tabset/vt300 
rm -f /usr/share/tabset/std 
rm -f /usr/share/tabset/vt100 
rm -f /usr/share/tabset/stdcrt 
rm -f /usr/share/terminfo/61 
rm -f /usr/share/terminfo/67 
rm -f /usr/share/terminfo/r/rxvt-xpm 
rm -f /usr/share/terminfo/r/rxvt-16color 
rm -f /usr/share/terminfo/r/rxvt-cygwin-native 
rm -f /usr/share/terminfo/r/rxvt-88color 
rm -f /usr/share/terminfo/r/rxvt-cygwin 
rm -f /usr/share/terminfo/r/rxvt 
rm -f /usr/share/terminfo/r/rxvt-color 
rm -f /usr/share/terminfo/r/rxvt-256color 
rm -f /usr/share/terminfo/r/rxvt-basic 
rm -f /usr/share/terminfo/r/rxvt+pcfkeys 
rm -f /usr/share/terminfo/u/unknown 
rm -f /usr/share/terminfo/45 
rm -f /usr/share/terminfo/73 
rm -f /usr/share/terminfo/g/gnome+pcfkeys 
rm -f /usr/share/terminfo/g/gnome-rh72 
rm -f /usr/share/terminfo/g/gnome-rh80 
rm -f /usr/share/terminfo/g/gnome-fc5 
rm -f /usr/share/terminfo/g/gnome 
rm -f /usr/share/terminfo/g/gnome-2007 
rm -f /usr/share/terminfo/g/gnome-2008 
rm -f /usr/share/terminfo/g/gnome-256color 
rm -f /usr/share/terminfo/g/gnome-rh90 
rm -f /usr/share/terminfo/g/gnome-rh62 
rm -f /usr/share/terminfo/s 
rm -f /usr/share/terminfo/s/screen-16color 
rm -f /usr/share/terminfo/s/sun-17 
rm -f /usr/share/terminfo/s/sun 
rm -f /usr/share/terminfo/s/screen-16color-bce-s 
rm -f /usr/share/terminfo/s/screen-256color-bce 
rm -f /usr/share/terminfo/s/sun-cgsix 
rm -f /usr/share/terminfo/s/screen.rxvt 
rm -f /usr/share/terminfo/s/sun-type4 
rm -f /usr/share/terminfo/s/sun-e-s 
rm -f /usr/share/terminfo/s/sun-cmd 
rm -f /usr/share/terminfo/s/screen.xterm-r6 
rm -f /usr/share/terminfo/s/sun-c 
rm -f /usr/share/terminfo/s/screen-w 
rm -f /usr/share/terminfo/s/screen.xterm-xfree86 
rm -f /usr/share/terminfo/s/sun-ss5 
rm -f /usr/share/terminfo/s/sun-e 
rm -f /usr/share/terminfo/s/sun-nic 
rm -f /usr/share/terminfo/s/sun-34 
rm -f /usr/share/terminfo/s/screen-16color-s 
rm -f /usr/share/terminfo/s/screen.linux 
rm -f /usr/share/terminfo/s/sun-12 
rm -f /usr/share/terminfo/s/screen-256color-bce-s 
rm -f /usr/share/terminfo/s/sun-24 
rm -f /usr/share/terminfo/s/sun-48 
rm -f /usr/share/terminfo/s/screen 
rm -f /usr/share/terminfo/s/sun-il 
rm -f /usr/share/terminfo/s/screen-bce 
rm -f /usr/share/terminfo/s/screen-256color-s 
rm -f /usr/share/terminfo/s/screen.mlterm 
rm -f /usr/share/terminfo/s/screen-s 
rm -f /usr/share/terminfo/s/screen.teraterm 
rm -f /usr/share/terminfo/s/screen-16color-bce 
rm -f /usr/share/terminfo/s/sun-s 
rm -f /usr/share/terminfo/s/sun-1 
rm -f /usr/share/terminfo/s/sun-color 
rm -f /usr/share/terminfo/s/screen.xterm-new 
rm -f /usr/share/terminfo/s/screen-256color 
rm -f /usr/share/terminfo/s/screen+fkeys 
rm -f /usr/share/terminfo/s/sun-s-e 
rm -f /usr/share/terminfo/75 
rm -f /usr/share/terminfo/A 
rm -f /usr/share/terminfo/A/ansi+idl1 
rm -f /usr/share/terminfo/A/ansi+idc 
rm -f /usr/share/terminfo/A/apple-soroc 
rm -f /usr/share/terminfo/A/apple-videx2 
rm -f /usr/share/terminfo/A/apple-vm80 
rm -f /usr/share/terminfo/A/apple-videx3 
rm -f /usr/share/terminfo/A/ansi-mono 
rm -f /usr/share/terminfo/A/ansi+pp 
rm -f /usr/share/terminfo/A/ansi+idl 
rm -f /usr/share/terminfo/A/ansi+csr 
rm -f /usr/share/terminfo/A/ansi-generic 
rm -f /usr/share/terminfo/A/ansi+sgr 
rm -f /usr/share/terminfo/A/ansi+cup 
rm -f /usr/share/terminfo/A/ansi-emx 
rm -f /usr/share/terminfo/A/ansi+sgrbold 
rm -f /usr/share/terminfo/A/ansi+sgrul 
rm -f /usr/share/terminfo/A/ansi+sgrso 
rm -f /usr/share/terminfo/A/ansi 
rm -f /usr/share/terminfo/A/ansi-color-2-emx 
rm -f /usr/share/terminfo/A/ansi-color-3-emx 
rm -f /usr/share/terminfo/A/ansi-mtabs 
rm -f /usr/share/terminfo/A/ansi+sgrdim 
rm -f /usr/share/terminfo/A/apple-uterm-vb 
rm -f /usr/share/terminfo/A/apple-ae 
rm -f /usr/share/terminfo/A/ansi+erase 
rm -f /usr/share/terminfo/A/apple-uterm 
rm -f /usr/share/terminfo/A/ansi+rep 
rm -f /usr/share/terminfo/A/ansi+tabs 
rm -f /usr/share/terminfo/A/ansi+local1 
rm -f /usr/share/terminfo/A/ansi+rca 
rm -f /usr/share/terminfo/A/ansi-mini 
rm -f /usr/share/terminfo/A/ansi+enq 
rm -f /usr/share/terminfo/A/ansi-nt 
rm -f /usr/share/terminfo/A/ansi-mr 
rm -f /usr/share/terminfo/A/ansi.sys 
rm -f /usr/share/terminfo/A/ansi.sys-old 
rm -f /usr/share/terminfo/A/apple-videx 
rm -f /usr/share/terminfo/A/ansi.sysk 
rm -f /usr/share/terminfo/A/apple-80 
rm -f /usr/share/terminfo/A/Apple_Terminal 
rm -f /usr/share/terminfo/A/ansi+inittabs 
rm -f /usr/share/terminfo/A/ansi+local 
rm -f /usr/share/terminfo/A/ansi-m 
rm -f /usr/share/terminfo/A/ansi+arrows 
rm -f /usr/share/terminfo/72 
rm -f /usr/share/terminfo/6b 
rm -f /usr/share/terminfo/65 
rm -f /usr/share/terminfo/6d 
rm -f /usr/share/terminfo/6c 
rm -f /usr/share/terminfo/63 
rm -f /usr/share/terminfo/64 
rm -f /usr/share/terminfo/m 
rm -f /usr/share/terminfo/m/mach-color 
rm -f /usr/share/terminfo/m/mach 
rm -f /usr/share/terminfo/m/mach-bold 
rm -f /usr/share/terminfo/41 
rm -f /usr/share/terminfo/c 
rm -f /usr/share/terminfo/c/cons25-koi8r-m 
rm -f /usr/share/terminfo/c/cons25-m 
rm -f /usr/share/terminfo/c/cons25-iso-m 
rm -f /usr/share/terminfo/c/cons25-koi8-r 
rm -f /usr/share/terminfo/c/cons25-iso8859 
rm -f /usr/share/terminfo/c/cons25 
rm -f /usr/share/terminfo/c/cygwin 
rm -f /usr/share/terminfo/70 
rm -f /usr/share/terminfo/d 
rm -f /usr/share/terminfo/d/dumb 
rm -f /usr/share/terminfo/v 
rm -f /usr/share/terminfo/v/vt102 
rm -f /usr/share/terminfo/v/vt100-putty 
rm -f /usr/share/terminfo/v/vt100-nav-w 
rm -f /usr/share/terminfo/v/vt100-s 
rm -f /usr/share/terminfo/v/vt102-w 
rm -f /usr/share/terminfo/v/vt102-nsgr 
rm -f /usr/share/terminfo/v/vt100+ 
rm -f /usr/share/terminfo/v/vt220+keypad 
rm -f /usr/share/terminfo/v/vt220 
rm -f /usr/share/terminfo/v/vt100-vb 
rm -f /usr/share/terminfo/v/vt220-nam 
rm -f /usr/share/terminfo/v/vt100+enq 
rm -f /usr/share/terminfo/v/vt220-w 
rm -f /usr/share/terminfo/v/vt102+enq 
rm -f /usr/share/terminfo/v/vt100-s-top 
rm -f /usr/share/terminfo/v/vt220-8bit 
rm -f /usr/share/terminfo/v/vt100-nam-w 
rm -f /usr/share/terminfo/v/vt220-js 
rm -f /usr/share/terminfo/v/vt100+fnkeys 
rm -f /usr/share/terminfo/v/vt100-w 
rm -f /usr/share/terminfo/v/vt52 
rm -f /usr/share/terminfo/v/vt100 
rm -f /usr/share/terminfo/v/vt100-w-nav 
rm -f /usr/share/terminfo/v/vt100-bot-s 
rm -f /usr/share/terminfo/v/vt100-w-nam 
rm -f /usr/share/terminfo/v/vt100+pfkeys 
rm -f /usr/share/terminfo/v/vt100-top-s 
rm -f /usr/share/terminfo/v/vt100-nav 
rm -f /usr/share/terminfo/v/vt100-nam 
rm -f /usr/share/terminfo/v/vt100-bm-o 
rm -f /usr/share/terminfo/v/vt220-8 
rm -f /usr/share/terminfo/v/vt220-old 
rm -f /usr/share/terminfo/v/vt100+keypad 
rm -f /usr/share/terminfo/v/vt100-am 
rm -f /usr/share/terminfo/v/vt100-s-bot 
rm -f /usr/share/terminfo/v/vt100-w-am 
rm -f /usr/share/terminfo/v/vt100-bm 
rm -f /usr/share/terminfo/x 
rm -f /usr/share/terminfo/x/xterm-256color 
rm -f /usr/share/terminfo/x/xterm+r6f2 
rm -f /usr/share/terminfo/x/xterm-color 
rm -f /usr/share/terminfo/x/xterm-16color 
rm -f /usr/share/terminfo/x/xterm-xf86-v40 
rm -f /usr/share/terminfo/x/xterm+88color 
rm -f /usr/share/terminfo/x/xterm+pce2 
rm -f /usr/share/terminfo/x/xterm+app 
rm -f /usr/share/terminfo/x/xterm-8bit 
rm -f /usr/share/terminfo/x/xterm-xi 
rm -f /usr/share/terminfo/x/xterm+pcc0 
rm -f /usr/share/terminfo/x/xterm+pcf2 
rm -f /usr/share/terminfo/x/xterm 
rm -f /usr/share/terminfo/x/xterm+noapp 
rm -f /usr/share/terminfo/x/xterm-basic 
rm -f /usr/share/terminfo/x/xterm+pcc1 
rm -f /usr/share/terminfo/x/xterm-r6 
rm -f /usr/share/terminfo/x/xterm-88color 
rm -f /usr/share/terminfo/x/xterm-xf86-v333 
rm -f /usr/share/terminfo/x/xterm-xfree86 
rm -f /usr/share/terminfo/x/xterm-vt220 
rm -f /usr/share/terminfo/x/xterm-hp 
rm -f /usr/share/terminfo/x/xterm-new 
rm -f /usr/share/terminfo/x/xterm-noapp 
rm -f /usr/share/terminfo/x/xterm+pc+edit 
rm -f /usr/share/terminfo/x/xterm-1003 
rm -f /usr/share/terminfo/x/xterm+sl-twm 
rm -f /usr/share/terminfo/x/xterm-pcolor 
rm -f /usr/share/terminfo/x/xterm-1002 
rm -f /usr/share/terminfo/x/xterm-sco 
rm -f /usr/share/terminfo/x/xterm+vt+edit 
rm -f /usr/share/terminfo/x/xterm-xf86-v43 
rm -f /usr/share/terminfo/x/xterm-xf86-v44 
rm -f /usr/share/terminfo/x/xterm+pcc3 
rm -f /usr/share/terminfo/x/xterm-24 
rm -f /usr/share/terminfo/x/xterm-old 
rm -f /usr/share/terminfo/x/xterm+pcf0 
rm -f /usr/share/terminfo/x/xterm+256color 
rm -f /usr/share/terminfo/x/xterm-r5 
rm -f /usr/share/terminfo/x/xterm+pcc2 
rm -f /usr/share/terminfo/x/xterm+pcfkeys 
rm -f /usr/share/terminfo/x/xterm+sl 
rm -f /usr/share/terminfo/x/xterm+edit 
rm -f /usr/share/terminfo/x/xterm-sun 
rm -f /usr/share/terminfo/x/xterm-bold 
rm -f /usr/share/terminfo/x/xterm-nic 
rm -f /usr/share/terminfo/x/xterm-vt52 
rm -f /usr/share/terminfo/x/xterm-xf86-v32 
rm -f /usr/share/terminfo/x/xterm-xf86-v33 
rm -f /usr/share/terminfo/E 
rm -f /usr/share/terminfo/E/Eterm-88color 
rm -f /usr/share/terminfo/E/eterm 
rm -f /usr/share/terminfo/E/Eterm-256color 
rm -f /usr/share/terminfo/E/Eterm-color 
rm -f /usr/share/terminfo/76 
rm -f /usr/share/terminfo/k 
rm -f /usr/share/terminfo/k/konsole-vt100 
rm -f /usr/share/terminfo/k/konsole-base 
rm -f /usr/share/terminfo/k/konsole-vt420pc 
rm -f /usr/share/terminfo/k/konsole 
rm -f /usr/share/terminfo/k/konsole-solaris 
rm -f /usr/share/terminfo/k/konsole-linux 
rm -f /usr/share/terminfo/k/konsole-16color 
rm -f /usr/share/terminfo/k/konsole+pcfkeys 
rm -f /usr/share/terminfo/k/konsole-xf3x 
rm -f /usr/share/terminfo/k/konsole-256color 
rm -f /usr/share/terminfo/k/konsole-xf4x 
rm -f /usr/share/terminfo/l 
rm -f /usr/share/terminfo/l/linux-lat 
rm -f /usr/share/terminfo/l/linux-koi8r 
rm -f /usr/share/terminfo/l/linux-vt 
rm -f /usr/share/terminfo/l/linux-basic 
rm -f /usr/share/terminfo/l/linux 
rm -f /usr/share/terminfo/l/linux-c-nc 
rm -f /usr/share/terminfo/l/linux-c 
rm -f /usr/share/terminfo/l/linux-m 
rm -f /usr/share/terminfo/l/linux-nic 
rm -f /usr/share/terminfo/l/linux-koi8 
rm -f /usr/share/terminfo/78 
rm -f /usr/share/terminfo/p 
rm -f /usr/share/terminfo/p/pcansi-43-m 
rm -f /usr/share/terminfo/p/putty-vt100 
rm -f /usr/share/terminfo/p/putty 
rm -f /usr/share/terminfo/p/pcansi-43 
rm -f /usr/share/terminfo/p/pcansi-33 
rm -f /usr/share/terminfo/p/pcansi-25-m 
rm -f /usr/share/terminfo/p/pcansi-m 
rm -f /usr/share/terminfo/p/putty-256color 
rm -f /usr/share/terminfo/p/pcansi-mono 
rm -f /usr/share/terminfo/p/pcansi 
rm -f /usr/share/terminfo/p/pcansi-25 
rm -f /usr/share/terminfo/p/pcansi-33-m 
rm -f /usr/share/dict 
rm -f /usr/share/gnupg 
rm -f /usr/share/gnupg/options.skel 
rm -f /usr/share/dpkg 
rm -f /usr/share/dpkg/ostable 
rm -f /usr/share/dpkg/triplettable 
rm -f /usr/share/dpkg/cputable 
rm -f /usr/share/dpkg/origins 
rm -f /usr/bin/gtar 
rm -f /usr/bin/dselect 
rm -f /usr/bin/cycc 
rm -f /usr/bin/dpkg-statoverride 
rm -f /usr/bin/dpkg-deb 
rm -f /usr/bin/dpkg-divert 
rm -f /usr/bin/cynject 
rm -f /usr/bin/update-alternatives 
rm -f /usr/bin/dpkg-split 
rm -f /usr/bin/uicache 
rm -f /usr/bin/dpkg-trigger 
rm -f /usr/bin/dpkg-maintscript-helper 
rm -f /usr/bin/env 
rm -f /usr/bin/gnutar 
rm -f /usr/bin/cycript 
rm -f /usr/bin/dpkg-query 
rm -f /usr/bin/apt 
rm -f /usr/bin/apt-get 
rm -f /usr/bin/dpkg 
rm -f /usr/libexec/cydia 
rm -f /usr/libexec/cydia/setnsfpn 
rm -f /usr/libexec/cydia/du 
rm -f /usr/libexec/cydia/cydo 
rm -f /usr/libexec/MSUnrestrictProcess 
rm -f /usr/libexec/substrate 
rm -f /usr/include/substrate.h 
rm -f /usr/include/dpkg 
rm -f /usr/include/dpkg/progress.h 
rm -f /usr/include/dpkg/error.h 
rm -f /usr/include/dpkg/dpkg.h 
rm -f /usr/include/dpkg/tarfn.h 
rm -f /usr/include/dpkg/varbuf.h 
rm -f /usr/include/dpkg/debug.h 
rm -f /usr/include/dpkg/version.h 
rm -f /usr/include/dpkg/atomic-file.h 
rm -f /usr/include/dpkg/namevalue.h 
rm -f /usr/include/dpkg/path.h 
rm -f /usr/include/dpkg/deb-version.h 
rm -f /usr/include/dpkg/pkg.h 
rm -f /usr/include/dpkg/file.h 
rm -f /usr/include/dpkg/subproc.h 
rm -f /usr/include/dpkg/color.h 
rm -f /usr/include/dpkg/trigdeferred.h 
rm -f /usr/include/dpkg/pkg-format.h 
rm -f /usr/include/dpkg/options.h 
rm -f /usr/include/dpkg/progname.h 
rm -f /usr/include/dpkg/parsedump.h 
rm -f /usr/include/dpkg/fdio.h 
rm -f /usr/include/dpkg/ehandle.h 
rm -f /usr/include/dpkg/buffer.h 
rm -f /usr/include/dpkg/macros.h 
rm -f /usr/include/dpkg/report.h 
rm -f /usr/include/dpkg/c-ctype.h 
rm -f /usr/include/dpkg/pkg-show.h 
rm -f /usr/include/dpkg/compress.h 
rm -f /usr/include/dpkg/pkg-array.h 
rm -f /usr/include/dpkg/pkg-list.h 
rm -f /usr/include/dpkg/triglib.h 
rm -f /usr/include/dpkg/pkg-spec.h 
rm -f /usr/include/dpkg/ar.h 
rm -f /usr/include/dpkg/command.h 
rm -f /usr/include/dpkg/program.h 
rm -f /usr/include/dpkg/dpkg-db.h 
rm -f /usr/include/dpkg/treewalk.h 
rm -f /usr/include/dpkg/glob.h 
rm -f /usr/include/dpkg/dir.h 
rm -f /usr/include/dpkg/pkg-queue.h 
rm -f /usr/include/dpkg/arch.h 
rm -f /usr/include/dpkg/string.h 
rm -f /usr/sbin/start-stop-daemon 
rm -f /usr/local/bin 
rm -f /usr/local/bin/wget 
rm -f /usr/local/bin/dbclient 
rm -f /usr/local/bin/filemon 
rm -f /usr/local/bin/dropbear 
rm -f /usr/local/bin/procexp 
rm -f /usr/local/bin/jtool 
rm -f /usr/local/bin/dropbearkey 
rm -f /usr/local/bin/dropbearconvert 
rm -f /usr/local/lib 
rm -f /usr/local/lib/zsh 
rm -f /usr/local/lib/zsh/5.0.8 
rm -f /usr/local/lib/zsh/5.0.8/zsh 
rm -f /usr/local/lib/zsh/5.0.8/zsh/termcap.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/zleparameter.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/example.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/tcp.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/newuser.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/deltochar.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/complete.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/mapfile.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/stat.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/compctl.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/zselect.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/parameter.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/datetime.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/socket.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/terminfo.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/clone.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/regex.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/attr.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/curses.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/files.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/system.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/zpty.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/zle.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/mathfunc.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/zutil.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/complist.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/zftp.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/cap.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/computil.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/zprof.so 
rm -f /usr/local/lib/zsh/5.0.8/zsh/langinfo.so 
rm -f /usr/lib/pkgconfig 
rm -f /usr/lib/pkgconfig/libdpkg.pc 
rm -f /usr/lib/cycript0.9 
rm -f /usr/lib/cycript0.9/org 
rm -f /usr/lib/cycript0.9/org/cycript 
rm -f /usr/lib/cycript0.9/org/cycript/NSLog.cy 
rm -f /usr/lib/cycript0.9/com 
rm -f /usr/lib/cycript0.9/com/saurik 
rm -f /usr/lib/cycript0.9/com/saurik/substrate 
rm -f /usr/lib/cycript0.9/com/saurik/substrate/MS.cy 
rm -f /usr/lib/libcycript.dylib 
rm -f /usr/lib/libcycript.jar 
rm -f /usr/lib/libapt-inst.dylib 
rm -f /usr/lib/libapt-pkg.dylib 
rm -f /usr/lib/libdpkg.a 
rm -f /usr/lib/libcrypto.1.0.0.dylib 
rm -f /usr/lib/libssl.1.0.0.dylib 
rm -f /usr/lib/apt/methods/gpgv 
rm -f /usr/lib/apt/methods/https 
rm -f /usr/lib/apt/methods/ftp 
rm -f /usr/lib/apt/methods/cdrom 
rm -f /usr/lib/apt/methods/file 
rm -f /usr/lib/apt/methods/rsh 
rm -f /usr/lib/apt/methods/gzip 
rm -f /usr/lib/apt/methods/xz 
rm -f /usr/lib/apt/methods/ssh 
rm -f /usr/lib/apt/methods/http 
rm -f /usr/lib/apt/methods/copy 
rm -f /usr/lib/apt/methods/rred 
rm -f /usr/lib/apt/methods/lzma 
rm -f /usr/lib/apt/methods/bzip2 
rm -f /usr/lib/apt/methods/store 
rm -f /usr/lib/apt/methods/mirror 
rm -f /usr/lib/libcycript.db 
rm -f /usr/lib/libcurl.4.dylib 
rm -f /usr/lib/libcycript.0.dylib 
rm -f /usr/lib/libcycript.cy 
rm -f /usr/lib/libsubstrate.dylib 
rm -f /usr/lib/libdpkg.la 
rm -f /usr/lib/libsubstrate.0.dylib 
rm -f /usr/lib/dpkg 
rm -f /usr/share/dpkg 
rm -f /usr/share/dpkg/architecture.mk 
rm -f /usr/share/dpkg/buildflags.mk 
rm -f /usr/share/dpkg/default.mk 
rm -f /usr/share/dpkg/ostable 
rm -f /usr/share/dpkg/pkg-info.mk 
rm -f /usr/share/dpkg/vendor.mk 
rm -f /usr/share/dpkg/triplettable 
rm -f /usr/share/dpkg/cputable 
rm -f /usr/share/dpkg/abitable 
rm -f /bin/cat 
rm -f /bin/launchctl 
rm -f /bin/pwd 
rm -f /bin/sed 
rm -f /bin/sleep 
rm -f /bin/stty 
rm -f /bin/date 
rm -f /bin/bzip2_64 
rm -f /bin/bash 
rm -f /bin/kill 
rm -f /bin/sh 
rm -f /bin/dd 
rm -f /bin/mkdir 
rm -f /bin/hostname 
rm -f /bin/rmdir 
rm -f /bin/mv 
rm -f /bin/ln 
rm -f /bin/ls 
rm -f /bin/cp 
rm -f /bin/chown 
rm -f /bin/zsh 
rm -f /bin/chmod 
rm -f /bin/rm 
rm -f /bin/bzip2 
rm -f /etc/zshrc 
rm -f /etc/dropbear 
rm -f /etc/profile 
rm -f /etc/alternatives 
rm -f /etc/alternatives/README 
rm -f /etc/dpkg 
rm -f /etc/dpkg/dselect.cfg.d 
rm -f /etc/dpkg/dpkg.cfg.d 
rm -f /var/lib/dpkg 
rm -f /var/lib/dpkg/updates 
rm -f /var/lib/dpkg/info 
rm -f /var/lib/dpkg/parts 
rm -f /var/lib/dpkg/alternatives 
rm -f /Library/MobileSubstrate/MobileSubstrate.dylib 
rm -f /Library/MobileSubstrate/DynamicLibraries/NoPlaceLikeHome.dylib 
rm -f /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Libraries 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Libraries/SubstrateLauncher.dylib 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Libraries/SubstrateBootstrap.dylib 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Libraries/SubstrateLoader.dylib 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Libraries/SubstrateInjection.dylib 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Headers 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Headers/CydiaSubstrate.h 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Commands 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Commands/cycc 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Commands/cynject 
rm -f /Library/Frameworks/CydiaSubstrate.framework/Info.plist 
rm -f /Library/test_inject_springboard.cy 
rm -f /Applications/Cydia.app/installing@2x.png 
rm -f /Applications/Cydia.app/iOS7-Default-736h-Portrait@3x.png 
rm -f /Applications/Cydia.app/install@2x.png 
rm -f /Applications/Cydia.app/folder@2x.png 
rm -f /Applications/Cydia.app/install7s@3x.png 
rm -f /Applications/Cydia.app/Icon7-Small@2x.png 
rm -f /Applications/Cydia.app/Cydia 
rm -f /Applications/Cydia.app/search@2x.png 
rm -f /Applications/Cydia.app/home-Selected.png 
rm -f /Applications/Cydia.app/icon.png 
rm -f /Applications/Cydia.app/Sections 
rm -f /Applications/Cydia.app/Sections/Terminal_Support.png 
rm -f /Applications/Cydia.app/Sections/Addons.png 
rm -f /Applications/Cydia.app/Sections/Widgets.png 
rm -f /Applications/Cydia.app/Sections/Carrier_Bundles.png 
rm -f /Applications/Cydia.app/Sections/Administration.png 
rm -f /Applications/Cydia.app/Sections/Data_Storage.png 
rm -f /Applications/Cydia.app/Sections/Messaging.png 
rm -f /Applications/Cydia.app/Sections/Wallpaper.png 
rm -f /Applications/Cydia.app/Sections/Themes.png 
rm -f /Applications/Cydia.app/Sections/Networking.png 
rm -f /Applications/Cydia.app/Sections/Ringtones.png 
rm -f /Applications/Cydia.app/Sections/Toys.png 
rm -f /Applications/Cydia.app/Sections/Games.png 
rm -f /Applications/Cydia.app/Sections/Books.png 
rm -f /Applications/Cydia.app/Sections/Multimedia.png 
rm -f /Applications/Cydia.app/Sections/Tweaks.png 
rm -f /Applications/Cydia.app/Sections/Archiving.png 
rm -f /Applications/Cydia.app/Sections/Java.png 
rm -f /Applications/Cydia.app/Sections/Keyboards.png 
rm -f /Applications/Cydia.app/Sections/Entertainment.png 
rm -f /Applications/Cydia.app/Sections/System.png 
rm -f /Applications/Cydia.app/Sections/Localization.png 
rm -f /Applications/Cydia.app/Sections/X_Window.png 
rm -f /Applications/Cydia.app/Sections/Text_Editors.png 
rm -f /Applications/Cydia.app/Sections/Fonts.png 
rm -f /Applications/Cydia.app/Sections/Utilities.png 
rm -f /Applications/Cydia.app/Sections/Productivity.png 
rm -f /Applications/Cydia.app/Sections/Development.png 
rm -f /Applications/Cydia.app/Sections/Dictionaries.png 
rm -f /Applications/Cydia.app/Sections/Education.png 
rm -f /Applications/Cydia.app/Sections/Packaging.png 
rm -f /Applications/Cydia.app/Sections/Site-Specific_Apps.png 
rm -f /Applications/Cydia.app/Sections/Health_and_Fitness.png 
rm -f /Applications/Cydia.app/Sections/Security.png 
rm -f /Applications/Cydia.app/Sections/Soundboards.png 
rm -f /Applications/Cydia.app/Sections/Scripting.png 
rm -f /Applications/Cydia.app/Sections/Planet-iPhones Mods.png 
rm -f /Applications/Cydia.app/Sections/Navigation.png 
rm -f /Applications/Cydia.app/Sections/Social.png 
rm -f /Applications/Cydia.app/Sections/Repositories.png 
rm -f /Applications/Cydia.app/home@2x.png 
rm -f /Applications/Cydia.app/Default-Portrait@2x.png 
rm -f /Applications/Cydia.app/search7.png 
rm -f /Applications/Cydia.app/search7@3x.png 
rm -f /Applications/Cydia.app/home7@2x.png 
rm -f /Applications/Cydia.app/home7@3x.png 
rm -f /Applications/Cydia.app/search7@2x.png 
rm -f /Applications/Cydia.app/install.png 
rm -f /Applications/Cydia.app/compose.png 
rm -f /Applications/Cydia.app/iOS7-Default-Portrait@2x.png 
rm -f /Applications/Cydia.app/installing.png 
rm -f /Applications/Cydia.app/iconClassic.png 
rm -f /Applications/Cydia.app/changes7s.png 
rm -f /Applications/Cydia.app/Icon7-Small@3x.png 
rm -f /Applications/Cydia.app/Default-Landscape@2x.png 
rm -f /Applications/Cydia.app/install7s@2x.png 
rm -f /Applications/Cydia.app/iOS7-Default-Portrait.png 
rm -f /Applications/Cydia.app/Icon-Small.png 
rm -f /Applications/Cydia.app/Default-Portrait.png 
rm -f /Applications/Cydia.app/home7s.png 
rm -f /Applications/Cydia.app/search7s@3x.png 
rm -f /Applications/Cydia.app/Icon-60@3x.png 
rm -f /Applications/Cydia.app/removing.png 
rm -f /Applications/Cydia.app/Default@2x.png 
rm -f /Applications/Cydia.app/changes7@3x.png 
rm -f /Applications/Cydia.app/iOS7-Default-Landscape@2x.png 
rm -f /Applications/Cydia.app/removing@2x.png 
rm -f /Applications/Cydia.app/Sections.plist 
rm -f /Applications/Cydia.app/Icon-60.png 
rm -f /Applications/Cydia.app/home7s@2x.png 
rm -f /Applications/Cydia.app/uicache 
rm -f /Applications/Cydia.app/unknown.png 
rm -f /Applications/Cydia.app/home-Selected@2x.png 
rm -f /Applications/Cydia.app/Icon-Small-40@2x.png 
rm -f /Applications/Cydia.app/home.png 
rm -f /Applications/Cydia.app/Icon-76@2x~ipad.png 
rm -f /Applications/Cydia.app/home7s@3x.png 
rm -f /Applications/Cydia.app/Icon-Small-50@2x.png 
rm -f /Applications/Cydia.app/menes 
rm -f /Applications/Cydia.app/menes/menes.js 
rm -f /Applications/Cydia.app/install7s.png 
rm -f /Applications/Cydia.app/icon-72.png 
rm -f /Applications/Cydia.app/Default-Landscape.png 
rm -f /Applications/Cydia.app/changes7@2x.png 
rm -f /Applications/Cydia.app/icon-72@2x.png 
rm -f /Applications/Cydia.app/Icon-60@2x.png 
rm -f /Applications/Cydia.app/search7s@2x.png 
rm -f /Applications/Cydia.app/search.png 
rm -f /Applications/Cydia.app/manage.png 
rm -f /Applications/Cydia.app/icon@2x.png 
rm -f /Applications/Cydia.app/configure.png 
rm -f /Applications/Cydia.app/folder.png 
rm -f /Applications/Cydia.app/iOS7-Default-667h@2x.png 
rm -f /Applications/Cydia.app/Icon-76~ipad.png 
rm -f /Applications/Cydia.app/changes7s@2x.png 
rm -f /Applications/Cydia.app/Default-568h@2x.png 
rm -f /Applications/Cydia.app/Assets.car 
rm -f /Applications/Cydia.app/manage7s@3x.png 
rm -f /Applications/Cydia.app/Purposes 
rm -f /Applications/Cydia.app/Purposes/x.png 
rm -f /Applications/Cydia.app/Purposes/daemon.png 
rm -f /Applications/Cydia.app/Purposes/library.png 
rm -f /Applications/Cydia.app/Purposes/commercial.png 
rm -f /Applications/Cydia.app/Purposes/console.png 
rm -f /Applications/Cydia.app/Purposes/uikit.png 
rm -f /Applications/Cydia.app/Purposes/extension.png 
rm -f /Applications/Cydia.app/manage7.png 
rm -f /Applications/Cydia.app/changes@2x.png 
rm -f /Applications/Cydia.app/manage7s@2x.png 
rm -f /Applications/Cydia.app/changes7s@3x.png 
rm -f /Applications/Cydia.app/search7s.png 
rm -f /Applications/Cydia.app/manage7s.png 
rm -f /Applications/Cydia.app/manage@2x.png 
rm -f /Applications/Cydia.app/chevron@2x.png 
rm -f /Applications/Cydia.app/Sources 
rm -f /Applications/Cydia.app/Sources/apt.bigboss.us.com.png 
rm -f /Applications/Cydia.app/installed.png 
rm -f /Applications/Cydia.app/changes.png 
rm -f /Applications/Cydia.app/iOS7-Default-736h-Landscape@3x.png 
rm -f /Applications/Cydia.app/Icon-Small-50.png 
rm -f /Applications/Cydia.app/install7.png 
rm -f /Applications/Cydia.app/install7@3x.png 
rm -f /Applications/Cydia.app/manage7@3x.png 
rm -f /Applications/Cydia.app/manage7@2x.png 
rm -f /Applications/Cydia.app/install7@2x.png 
rm -f /Applications/Cydia.app/Default.png 
rm -f /Applications/Cydia.app/iOS7-Default-Landscape.png 
rm -f /Applications/Cydia.app/changes7.png 
rm -f /Applications/Cydia.app/error.html 
rm -f /Applications/Cydia.app/iOS7-Default@2x.png 
rm -f /Applications/Cydia.app/Icon7-Small.png 
rm -f /Applications/Cydia.app/Icon-Small-40.png 
rm -f /Applications/Cydia.app/localize.js 
rm -f /Applications/Cydia.app/Icon-Small@2x.png 
rm -f /Applications/Cydia.app/installed@2x.png 
rm -f /Applications/Cydia.app/reload.png 
rm -f /Applications/Cydia.app/store 
rm -f /Applications/Cydia.app/iOS7-Default-568h@2x.png 
rm -f /Applications/Cydia.app/home7.png 
rm -f /usr/local/lib/libluajit.a 
rm -f /var/tweak/com.r333d.jjjj 
rm -f /var/tweak/com.r333d.jjjj/lua 
rm -f /var/tweak/com.r333d.jjjj/lua/ui 
rm -f /var/tweak/com.r333d.jjjj/lua/ui/textbox.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/ui/filtertable.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/ui/searchbar.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/ui/cell.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/ui/scroll.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/ui/table.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/ui/gesture.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/ui/button.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/init.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/page 
rm -f /var/tweak/com.r333d.jjjj/lua/page/repos.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/page/installed.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/page/browse.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/res 
rm -f /var/tweak/com.r333d.jjjj/lua/res/globe.png 
rm -f /var/tweak/com.r333d.jjjj/lua/ns 
rm -f /var/tweak/com.r333d.jjjj/lua/ns/websocket.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/ns/http.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/ns/target.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/main.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/depiction.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/objc.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/screenshot.png 
rm -f /var/tweak/com.r333d.jjjj/lua/deb.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/config.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/constants.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/README.md 
rm -f /var/tweak/com.r333d.jjjj/lua/object.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/util.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/repo.lua 
rm -f /var/tweak/com.r333d.jjjj/lua/cdef 
rm -f /var/tweak/com.r333d.jjjj/lua/cdef/init.lua 
rm -f /Applications/jjjj.app 
rm -f /Applications/jjjj.app/iOS7-Default-736h-Portrait@3x.png 
rm -f /Applications/jjjj.app/entitlements.xml 
rm -f /Applications/jjjj.app/jjjj.exe 
rm -f /Applications/jjjj.app/iOS7-Default-Portrait@2x.png 
rm -f /Applications/jjjj.app/iOS7-Default-Portrait.png 
rm -f /Applications/jjjj.app/iOS7-Default-Landscape@2x.png 
rm -f /Applications/jjjj.app/Icon@2x.png 
rm -f /Applications/jjjj.app/iOS7-Default-667h@2x.png 
rm -f /Applications/jjjj.app/iOS7-Default-736h-Landscape@3x.png 
rm -f /Applications/jjjj.app/iOS7-Default-Landscape.png 
rm -f /Applications/jjjj.app/iOS7-Default@2x.png 
rm -f /Applications/jjjj.app/Info.plist
rm -f /Applications/jjjj.app/setuid
rm -f /Applications/jjjj.app/iOS7-Default-568h@2x.png
echo ""
echo "  [+]  Uninstallation finished"
echo "  [+]  Please reboot"